language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - cd app
  - npm install -g npm@6
install:
  - npm rebuild node-sass
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./app/build/
  on:
    branch: master