language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - cd home-app
script:
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sems.dev
  project: ./home-app/build/
on:
  branch: master
