language: node_js
node_js:
  - "8.11.1"
cache:
  directories:
    - node_modules
before_install:
  - cd home-app
  - npm install -g npm@4
install:
  - npm rebuild node-sass
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./home-app/build/
  on:
    branch: master