language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd home-app/
  - npm install
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sems.dev
  project: ./home-app/build/
on:
  branch: master